jwt:
   issuer: issuer
spring:
   datasource:
      url: jdbc:h2:file:./target/bestbuy;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
      username: best
      password: best
      driverClassName: org.h2.Driver
   test:
      database:
         replace: none
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            show_sql: false
            use_sql_comments: false
            format_sql: false
            dialect: org.hibernate.dialect.H2Dialect
            metadata_builder_contributor: br.com.estanislau.bestbuy.config.SqlFunctionsMetadataBuilderContributor
            temp:
               use_jdbc_metadata_defaults: false
   liquibase:
      change-log: classpath:/db-scripts/db.changelog.xml
      contexts: test
   main:
      allow-bean-definition-overriding: true