server:
  port : 8081
liquibase:
   change-log: classpath:/db-scripts/db.changelog.xml
logging:
   level:
#      root: DEBUG
      org:
         springframework:
            web: DEBUG
spring:
   datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:6433/bestbuy
        name: bestbuy
        username: postgres
        password: gloria
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            show_sql: false
            use_sql_comments: true
            format_sql: true
            metadata_builder_contributor: br.com.estanislau.bestbuy.config.SqlFunctionsMetadataBuilderContributor
            temp:
               use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   liquibase:
      enabled: false